/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.8.0"
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(project(":patcher"))
    implementation("io.github.microutils:kotlin-logging:4.0.0-beta-2")
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0")
    implementation("commons-cli:commons-cli:1.5.0")
}

application {
    // Define the main class for the application.
    mainClass.set("cappatchino.cli.MainKt")
}
